import { Mulish } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import AuthSessionProvider from '@/components/AuthSessionProvider';
import Footer from '@/components/footer/Footer';

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000'],
});

export const metadata = {
  title: 'Expenditcher | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${mulish.className} min-h-dvh justify-between container mx-auto select-none px-4 lg:px-8 flex flex-col bg-white`}>
        <AuthSessionProvider>
          <Navbar />
          <div className='w-full min-h-[calc(100dvh-6rem)] overflow-x-hidden'>
            {children}
          </div>
          <Footer />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
